- alias: EE Init Solar 
  id: ee_init_solar
  description: 'Determine todays rates as to workday or holiday'
  triggers:
  - trigger: homeassistant
    event: start
  - trigger: template
    value_template: "{{ states(this.entity_id) == 'on' }}" 
  conditions: []
  actions:
  - variables:
      whiles: >-
        {{ 
          states.automation | 
          selectattr('object_id', 'match', 'ee_while_') | 
          selectattr('state', 'eq', 'on') |
          map(attribute='entity_id') | 
          list 
        }}
  - if:
    - condition: template
      value_template: "{{ whiles | count > 1 }}"
    then:
    - action: automation.turn_off
      metadata: {}
      data:
        stop_actions: true
      target:
        entity_id:
          - automation.ee_while_zn
          - automation.ee_while_dl
          - automation.ee_while_cp
    - action: automation.turn_on
      metadata: {}
      data: {}
      target:
        entity_id: automation.ee_while_cp
    - delay:
        hours: 0
        minutes: 0
        seconds: 5
        milliseconds: 0
  - action: automation.trigger
    metadata: {}
    data:
      skip_condition: true
    target:
      entity_id: automation.ee_read_envoy_tariff
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - action: automation.trigger
    metadata: {}
    data:
      skip_condition: true
    target:
      entity_id: automation.ee_read_envoy_relay
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - action: automation.trigger
    metadata: {}
    data:
      skip_condition: true
    target:
      entity_id: automation.ee_read_envoy_xml_info
  mode: single
