- alias: EE Set is TOU Workday
  id: ee_set_is_tou_workday
  description: 'Determine todays rates as to workday or holiday'
  triggers:
  - trigger: time
    at: 00:15:00
  - trigger: homeassistant
    event: start
  - trigger: template
    value_template: "{{ states(this.entity_id) == 'on' }}" 
  conditions: []
  actions:
  - action: input_boolean.turn_off
    metadata: {}
    data: {}
    target:
      entity_id:
        - input_boolean.ee_solar_is_cloudy
        - input_boolean.ee_solar_is_tou_workday
        - input_boolean.ee_solar_is_off_season
  - if:
    - condition: and
      conditions:
      - condition: time
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
      - condition: template
        value_template: "{{ states('calendar.utility_tou_holidays') != 'on' }}"
    then:
    - action: input_boolean.turn_on
      metadata: {}
      data: {}
      target:
        entity_id: input_boolean.ee_solar_is_tou_workday
  - if:
      - condition: template
        value_template: "{{ now().month <= 5 or now().month >= 10 }}"
    then:
    - action: input_boolean.turn_on
      metadata: {}
      data: {}
      target:
        entity_id: input_boolean.ee_solar_is_off_season
  - action: input_number.set_value
    metadata: {}
    data:
      value: 0
    target:
      entity_id: input_number.ee_observed_solar_production_max
  - variables:
      tidx: "{{ trigger.idx }}"
  - if:
    - condition: template
      value_template: "{{ tidx != 0 }}"
    then:
    - action: automation.turn_off
      metadata: {}
      data:
        stop_actions: true
      target:
        entity_id:
          - automation.ee_while_zn
          - automation.ee_while_dl
          - automation.ee_while_cp
    - action: automation.turn_on
      metadata: {}
      data: {}
      target:
        entity_id: automation.ee_while_cp
    - delay:
        hours: 0
        minutes: 0
        seconds: 5
        milliseconds: 0
    - action: automation.trigger
      metadata: {}
      data:
        skip_condition: true
      target:
        entity_id:
        - automation.ee_read_envoy_tariff
    - delay:
        hours: 0
        minutes: 0
        seconds: 5
        milliseconds: 0
    - action: automation.trigger
      metadata: {}
      data:
        skip_condition: true
      target:
        entity_id:
        - automation.ee_read_envoy_relay
    - delay:
        hours: 0
        minutes: 0
        seconds: 5
        milliseconds: 0
    - action: automation.trigger
      metadata: {}
      data:
        skip_condition: true
      target:
        entity_id:
        - automation.ee_read_envoy_xml_info
  mode: single
