- alias: EE Solar Controller
  id: ee_solar_controller
  description: "Change Envoy Tariff for desired battery usage"
  trigger_variables:
    ZN80_M_8: ZN80/M-8
    ZN80_5p_8: ZN80/5p-8
    ZN96_M_5: ZN96/M-4p
    DL65_5p_8: DL65/5p-8
  triggers:
    - alias: Go ZN Workday
      trigger: template
      id: Go ZN Workday
      value_template: |-
        {{ 
          states('input_boolean.ee_solar_is_tou_workday') == 'on' 
            and
          states('input_number.ee_observed_solar_production') | int(0) >= 925000
            and
          states('input_number.ee_solar_generation_forecast') | int(0) > 
              states('sensor.ee_envoy_battery_charge_needed') | int(0) 
            and
          states('input_number.ee_solar_state_controller_counter') | int(0) == 0 
            and
          states('input_text.ee_solar_envoy_tariff_name') != ZN80_M_8 
            and
          states('input_boolean.ee_utilities_booted') == 'on'
        }}
      for:
        seconds: 4
    - trigger: template
      alias: Stop ZN Workday
      id: Stop ZN Workday
      value_template: |-
        {{
          states('input_boolean.ee_solar_is_tou_workday') == 'on' 
            and
          states('input_number.ee_solar_generation_forecast') | int(0) < 
              states('sensor.ee_envoy_battery_charge_needed') | int(-1)
            and
          8 <= states('input_number.ee_hour_of_day') | int(0) <= 15
            and
          states('input_text.ee_solar_envoy_tariff_name') == ZN80_M_8 
            and
          states('input_number.ee_observed_charge') | int(0) <= 97 
            and
          states('input_boolean.ee_utilities_booted') == 'on'
        }}
      for:
        minutes: 30
    - trigger: template
      alias: Go ZN Weekend/Holiday
      id: Go ZN Weekend
      value_template: |-
        {{ 
          states('input_boolean.ee_solar_is_tou_workday') == 'off' 
            and
          states('input_number.ee_observed_solar_production') | int(0) >= 925000
            and
          states('input_number.ee_solar_generation_forecast') | int(0) > 
              states('sensor.ee_envoy_battery_charge_needed') | int(0) 
            and
          states('input_number.ee_solar_state_controller_counter') | int(0) == 0 
            and
          states('input_text.ee_solar_envoy_tariff_name') != ZN96_M_5 
            and
          states('input_boolean.ee_utilities_booted') == 'on'
        }}
      for:
        seconds: 4
    - trigger: template
      alias: Stop ZN Weekend/Holiday
      id: Stop ZN Weekend
      value_template: |-
        {{
          states('input_boolean.ee_solar_is_tou_workday') == 'off' 
            and
          states('input_number.ee_solar_generation_forecast') | int(0) < 
              states('sensor.ee_envoy_battery_charge_needed') | int(-1)
            and
          8 <= states('input_number.ee_hour_of_day') | int(0) <= 15
            and
          states('input_text.ee_solar_envoy_tariff_name') == ZN96_M_5 
            and
          states('input_number.ee_observed_charge') | int(0) <= 97 
            and
          states('input_boolean.ee_utilities_booted') == 'on'
        }}
      for:
        minutes: 30
    - trigger: time
      alias: Go DL?
      id: Go DL?
      at: "16:45:00"
    - trigger: state
      alias: Booted
      id: Booted
      entity_id:
        - input_boolean.ee_utilities_booted
      to:
        - "on"
  conditions: []
  actions:
    - variables:
        time_now: "{{ now() }}"
        timestamp: "{{ (time_now | as_datetime).timestamp() | int(0) }}"
        summer: "{{ states('input_boolean.ee_solar_is_summer_season') == 'on' }}"
        workday: "{{ states('input_boolean.ee_solar_is_tou_workday') == 'on' }}"
        current_tariff: "{{ states('input_text.ee_solar_envoy_tariff_name') }}"
        doit: false
    - choose:
        - conditions:
            - condition: trigger
              id: Go ZN Workday
          sequence:
            - variables:
                tariff:
                  time: "{{ timestamp }}"
                  name: "{{ ZN80_M_8 }}"
                  peak_rule: ZN
                  peak_start: |-
                    {{ 
                      (time_now | as_datetime).hour * 60 + (time_now | as_datetime).minute
                    }}
                  peak_end: 961
                  second_start: 1021
                  second_end: 1201
                  reserve: 78
                doit: true
            - action: input_number.increment
              metadata: {}
              target:
                entity_id: input_number.ee_solar_state_controller_counter
              data: {}
        - conditions:
            - condition: trigger
              id: Stop ZN Workday
          sequence:
            - variables:
                tariff:
                  time: "{{ timestamp }}"
                  name: "{{ DL65_5p_8 if summer else ZN80_5p_8 }}"
                  peak_rule: "{{ 'DL' if summer else 'ZN' }}"
                  peak_start: 1021
                  peak_end: 1201
                  reserve: "{{ 65 if summer else 78 }}"
                doit: true
        - conditions:
            - condition: trigger
              id: Go ZN Weekend
          sequence:
            - variables:
                tariff:
                  time: "{{ timestamp }}"
                  name: "{{ ZN96_M_5 }}"
                  peak_rule: ZN
                  peak_start: |-
                    {{ 
                      (time_now | as_datetime).hour * 60 + (time_now | as_datetime).minute
                    }}
                  peak_end: 930
                  reserve: 82
                doit: true
            - action: input_number.increment
              metadata: {}
              target:
                entity_id: input_number.ee_solar_state_controller_counter
              data: {}
        - conditions:
            - condition: trigger
              id: Stop ZN Weekend
          sequence:
            - variables:
                tariff:
                  time: "{{ timestamp }}"
                  name: CPCP
                  peak_rule: ZN
                  peak_start: 660
                  peak_end: 665
                  reserve: 96
                doit: true
        - conditions:
            - condition: trigger
              id:
                - Go DL?
                - Booted
          sequence:
            - if:
                - condition: and
                  conditions:
                    - condition: template
                      value_template: "{{ workday }}"
                    - condition: or
                      conditions:
                        - condition: template
                          value_template: "{{ trigger.id == 'Go DL?' }}"
                        - condition: time
                          after: "16:40:00"
                          before: "20:00:00"
              then:
                - if:
                    - condition: template
                      value_template: |-
                        {{ 
                          summer 
                            and
                          current_tariff != DL65_5p_8
                        }}
                  then:
                    - variables:
                        tariff:
                          time: "{{ timestamp }}"
                          name: "{{ DL65_5p_8 }}"
                          peak_rule: DL
                          peak_start: 1021
                          peak_end: 1201
                          reserve: 65
                        doit: true
                - if:
                    - condition: template
                      value_template: |-
                        {{ 
                          not summer
                            and 
                          current_tariff != ZN80_5p_8
                            and
                          current_tariff != ZN80_M_8
                        }}
                  then:
                    - variables:
                        tariff:
                          time: "{{ timestamp }}"
                          name: "{{ ZN80_5p_8 }}"
                          peak_rule: ZN
                          peak_start: 1021
                          peak_end: 1201
                          reserve: 65
                        doit: true
    - if:
        - condition: template
          value_template: "{{ doit }}"
      then:
        - action: input_text.set_value
          metadata: {}
          target:
            entity_id: input_text.ee_solar_envoy_tariff_parameters
          data:
            value: "{{ tariff }}"
        - action: input_text.set_value
          metadata: {}
          target:
            entity_id: input_text.ee_solar_envoy_tariff_name
          data:
            value: "{{ tariff.name }}"
        - action: input_text.set_value
          metadata: {}
          target:
            entity_id: input_text.ee_solar_envoy_tariff_time
          data:
            value: "{{ tariff.time }}"
        - action: notify.persistent_notification
          metadata: {}
          data:
            message: |-
              {{ trigger.id }}
              {{ tariff.name }}
              {{ now().strftime("%y-%m-%d %H:%M:%S") }}
  mode: single
