- alias: EE Wake Battery
  id: ee_solar_wake_battery
  description: "Poke Envoy tariff if battery is not discharging when it should be."
  triggers:
    - trigger: template
      value_template: |-
        {{
          states('input_boolean.ee_solar_is_tou_workday') == 'on' 
            and
          17 <= states('input_number.ee_hour_of_day') | int <= 19
            and
          states('input_number.ee_observed_battery_flow') | int == 0
            and
          states('input_number.ee_observed_charge') | int - 2 >=
              states('input_number.ee_observed_tariff_battery_reserve') | int
        }}
      for:
        minutes: 1
  conditions: []
  actions:
    - variables:
        time_now: "{{ now().timestamp() | int }}"
        params: |-
          {{ 
            states('input_text.ee_solar_envoy_tariff_parameters')
            .replace("'", '"') 
            | from_json
          }}
    - action: input_text.set_value
      metadata: {}
      target:
        entity_id: input_text.ee_solar_envoy_tariff_parameters
      data:
        value: "{{ dict(params, time=time_now) }}"
    - action: input_text.set_value
      metadata: {}
      target:
        entity_id: input_text.ee_solar_envoy_tariff_time
      data:
        value: "{{ time_now }}"
    - action: notify.persistent_notification
      metadata: {}
      data:
        message: Waking Battery {{ now().strftime("%y-%m-%d %H:%M:%S") }}
  mode: single
